'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Home

    '''<summary>
    '''lbltodayProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltodayProfit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblmonthProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmonthProfit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblmonthRevenue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmonthRevenue As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lvlmonthCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvlmonthCost As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblOnDelivery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnDelivery As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblcustomerRegister control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcustomerRegister As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblpendingOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpendingOrder As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblcancelOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcancelOrder As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GvOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GvOrders As Global.System.Web.UI.WebControls.GridView
End Class
