'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CheckOut

    '''<summary>
    '''usrName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usrName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''usrCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usrCountry As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''usrEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usrEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''usrPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usrPhone As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''usrAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usrAddress As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''usrState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usrState As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''usrPostal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usrPostal As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''GvProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GvProducts As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''subtotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents subtotal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''totalAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents totalAmount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnBuy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuy As Global.System.Web.UI.WebControls.Button
End Class
